apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imageupdateautomation.yaml
  - backend-imagerepository.yaml
  - backend-imagepolicy.yaml
  - frontend-imagerepository.yaml
  - frontend-imagepolicy.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - ingress.yaml
  - redis-deployment.yaml
  - redis-service.yaml
