apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage-pvc.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  # - imagerepository.yaml
  # - imagepolicy.yaml
  # - imageupdateautomation.yaml
