apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - neuland-website
  - member-id
  - cl-events
  - ist-informatik-sexy
  - pretix
