apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aptabase-auth
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - analytics.neuland.app
      secretName: monitoring-tls
  rules:
    - host: analytics.neuland.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aptabase
                port:
                  number: 8080
