apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - clickhouse-deployment.yaml
  - clickhouse-service.yaml
  - pvc.yaml
  - aptabase-db-deployment.yaml
  - aptabase-db-service.yaml
  - aptabase-db-pvc.yaml
