apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - neuland-next-staging
  - neuland-next-prod
  - neuland-next-docs
  # - ersti-kit-staging
  - shared-database
  - neuland-api-prod
  - neuland-api-staging
  - neuland-dashboard
  - ersti-kit-prod
  - reimanns-scraper
  - mensa-scraper
