---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scraper-cronjob.yaml
  - scraper-statefulset.yaml
  - scraper-service.yaml
  - scraper-imagerepository.yaml
  - scraper-imagepolicy.yaml
  - scraper-imageupdateautomation.yaml
  - leaderboard-deployment.yaml
  - leaderboard-service.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - ingress.yaml
  - certificate.yaml

