apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - leaderboard-deployment.yaml
  - leaderboard-imagerepository.yaml
  - leaderboard-imagepolicy.yaml
  - leaderboard-service.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - ingress.yaml
  - certificate.yaml
