---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scraper-statefulset.yaml
  - scraper-service.yaml
  - scraper-imagerepository.yaml
  - scraper-imagepolicy.yaml
  - scraper-imageupdateautomation.yaml

