apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assets
  namespace: neuland-app
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - assets.neuland.app
      secretName: neuland-app-prod-tls
  rules:
    - host: assets.neuland.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assets
                port:
                  name: http
