apiVersion: v1
kind: Service
metadata:
  name: assets
  namespace: neuland-app
spec:
  type: ClusterIP
  selector:
    app: assets
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
