---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imageupdateautomation.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml
  - ingress.yaml
  - backend-imagerepository.yaml
  - backend-imagepolicy.yaml
  - frontend-imagerepository.yaml
  - frontend-imagepolicy.yaml
  - strip-api-middleware.yaml