apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ersti-kit-staging
  namespace: neuland-app
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dev.ersti.neuland.app
      secretName: neuland-app-dev-tls
  rules:
    - host: dev.ersti.neuland.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ersti-kit-staging
                port:
                  number: 3000
