apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - traefik.yaml
  - metallb.yaml
  - hcloud-floater.yaml
  - longhorn.yaml
  - longhorn-s3-sealed.yaml
  - hcloud-token-sealed.yaml
  - sops-secrets-source.yaml
  - sops-secrets-kustomization.yaml
  - test.yaml
