---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-infra
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m0s
  path: ./clusters/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: sops-infra
