apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neuland-website
  namespace: verein-ext
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.neuland-ingolstadt.de
        - neuland-ingolstadt.de
        - neuland.ing
      secretName: verein-ext-tls
  rules:
    - host: www.neuland-ingolstadt.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neuland-website
                port:
                  number: 3000
    - host: neuland-ingolstadt.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neuland-website
                port:
                  number: 3000
    - host: neuland.ing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neuland-website
                port:
                  number: 3000
