apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: verein-ext-cert
  namespace: verein-ext
spec:
  secretName: verein-ext-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  # Domains specific to verein-ext namespace
  dnsNames:
    - www.neuland-ingolstadt.de
    - id.neuland-ingolstadt.de
    - id.neuland.ing
    - neuland-ingolstadt.de
    - neuland.ing
    - ist.informatik.sexy
    - cl.neuland-ingolstadt.de
    - cl.neuland.ing
