apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reimanns-scraper
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: reimanns-scraper-config
  path: ./
  prune: true
  wait: true
