apiVersion: v1
kind: Service
metadata:
  name: membership-informatik-sexy
  namespace: verein-int
spec:
  type: ClusterIP
  selector:
    app: membership-informatik-sexy
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
