apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - uptime-kuma - deprecated -> replaced by gatus
  - aptabase
  - kube-prometheus-stack
  - loki
  - gatus
