apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pretix
  namespace: verein-ext
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - tickets.neuland-ingolstadt.de
      secretName: verein-ext-tls
  rules:
    - host: tickets.neuland-ingolstadt.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pretix
                port:
                  number: 80
