apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pretix-deployment.yaml
  - pretix-service.yaml
  - pretix-data-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - ingress.yaml
